pipeline:
  test:
    image: node:${NODE_VERSION}
    commands:
      - npm install
      - npm run test

# Notify build status to rocketchat room
# Add webhook-rocketchat to your pipeline
  webhook-rocketchat:
    image: plugins/webhook
    secrets: [webhook_urls]
    method: POST
    content_type: application/json
    template: |
      {
        "hook": "Drone CI/CD",
        "event": "{{ build.event }}",
        "owner": "{{ repo.owner }}",
        "repo": "{{ repo.name }}",
        "branch": "{{ build.branch }}",
        "author": "{{ build.author }}",
        "link": "{{ build.link }}",
        "status": "{{ build.status }}"
      }
    debug: true
    when:
      status: [ success, failure ]
# Add webhook-rocketchat to your pipeline

matrix:
  NODE_VERSION:
    - latest
    - 8