version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 8000:8000
      - 9000
    volumes:
      - drone-server-data:/var/lib/drone/
    restart: always

    # ! gitea webhook target URL `MUST` be access-availabled IP (ex. 192.168.1.161)
    environment:
      - GIN_MODE=release
      - DRONE_OPEN=true
      - DRONE_HOST=http://drone-server
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=${GITEA_URL}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}

volumes:
  drone-server-data:
