aws-instances:
  hosts:
    relajet-kws-web:
      # Get ansible_host from terraform output
      ansible_host: ec2-34-239-184-154.compute-1.amazonaws.com
      ansible_user: ubuntu

  vars:
    # Must be full node version
    node_version: 9.11.2
    application_repo_url: http://114.32.164.241:10078/RELAJET/RelaJet-KWS-web.git
    application_dest: /home/ubuntu/example
    application_dist_folder_name: dist